# ----- Dispositivos de entrada -----

input "type:keyboard" {
    xkb_layout us,latam
    xkb_numlock enabled
    xkb_options grp:rctrl_toggle
}

input "tyoe:pointer" {
    accel_profile "adaptive"    # Options: "flat" or "adaptive"
    pointer_accel 0.0
}

input "type:touchpad" {
    tap enabled
    tap_button_map lrm

    drag_lock disabled

    natural_scroll enabled
    scroll_method two_finger

    accel_profile adaptive
    pointer_accel 0.4 

    click_method clickfinger
    middle_emulation enabled 

    dwt enabled
    dwtp enabled
}
